### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'soc')

### ISSUE THREAD

**Issue by alucas79** [zerwuff/homebridge-alphaess#10]
**Describe The Bug:**
thanks for writing this plugin, when installing via the UI and configuring the plugin, it is throwing an Exception about TypeError SOC Null.
appid,app secret and serial are configured, im not using mqtt so they are blank currently.
i have no other plugins installed at this stage as i am trying to get this one working.

**To Reproduce:**
fresh install of Homebridge either on docker or Ubuntu gives the same error, i have tried previous versions of both homebridge (1.1.0 so 1.6.1 of homebridge, and previous versions of the alphaess Plugin) 

**Expected behavior:**
SOC should return a value and not give this error.

**Logs:**
[3/27/2024, 10:58:47 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 3651) is running on port 51090.
[3/27/2024, 10:58:47 PM] TypeError: Cannot read properties of null (reading 'soc')
    at AlphaService.storeData (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:381:54)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:366:16)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:185:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
[3/27/2024, 10:58:47 PM] TypeError: Cannot read properties of null (reading 'soc')
    at AlphaService.storeData (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:381:54)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:366:16)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:185:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
[3/27/2024, 10:58:47 PM] Got SIGTERM, shutting down Homebridge...
```
Show the Homebridge logs here, remove any sensitive information.
[3/27/2024, 11:05:38 PM] TypeError: Cannot read properties of null (reading 'soc')
    at AlphaService.storeData (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:381:54)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:366:16)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:185:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
[3/27/2024, 11:05:43 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[3/27/2024, 11:05:48 PM] [HB Supervisor] Restarting Homebridge...
[3/27/2024, 11:05:48 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[3/27/2024, 11:05:48 PM] [HB Supervisor] Started Homebridge v1.6.1 with PID: 12624
[3/27/2024, 11:05:49 PM] Loaded config.json with 0 accessories and 2 platforms.
[3/27/2024, 11:05:49 PM] Loaded 0 cached accessories from cachedAccessories.
[3/27/2024, 11:05:49 PM] ---
[3/27/2024, 11:05:49 PM] Loaded plugin: homebridge-alphaess@2.83.0
[3/27/2024, 11:05:49 PM] Registering platform 'homebridge-alphaess.AlphaEssPlatform'
[3/27/2024, 11:05:49 PM] ---
[3/27/2024, 11:05:49 PM] Loading 2 platforms...
[3/27/2024, 11:05:49 PM] [AlphaEssPlatform] Initializing AlphaEssPlatform platform...
[3/27/2024, 11:05:49 PM] [AlphaEssPlatform] Alpha Ess Platform Plugin started 
[3/27/2024, 11:05:49 PM] Initializing platform accessory 'AlphaEssBattery'...
[3/27/2024, 11:05:49 PM] Initializing platform accessory 'EnergyTriggerPlugin'...
Setup Payload:

Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     

    └────────────┘     
                       
[3/27/2024, 11:05:49 PM] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 3651) is running on port 51090.
[3/27/2024, 11:05:50 PM] TypeError: Cannot read properties of null (reading 'soc')
    at AlphaService.storeData (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:381:54)
    at Request._callback (/var/lib/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:366:16)
    at Request.self.callback (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:185:22)
    at Request.emit (node:events:517:28)
    at Request.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:517:28)
    at IncomingMessage.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alphaess/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:631:28)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge 3651",
        "username": "",
        "port": 51090,
        "pin": "",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "alphaUrl": "https://openapi.alphaess.com/api",
            "appid": "xxxxx",
            "appsecret": "xxxxx",
            "serialnumber": "xxxxx",
            "powerLoadingThreshold": 1500,
            "socLoadingThreshold": 50,
            "refreshTimerInterval": 60000,
            "power_image_filename": "/tmp/alpha_power_image.png",
            "logrequestdata": true,
            "tibberEnabled": false,
            "tibberLoadBatteryEnabled": false,
            "tibberLoadingMinutes": 60,
            "tibberThresholdSOC": 60,
            "tibberThresholdEur": 0.01,
            "triggerImageFilename": "/tmp/tibber_image.png",
            "platform": "AlphaEssPlatform"
        }
    ]
}
~          
```

**Screenshots:**

**Environment:**

* **Plugin Version**:2.83.0
* **Homebridge Version**: 1.6.1
* **Node.js Version**: 18.18.2
* **NPM Version**: 9.8.1
* **Operating System**: ubuntu and docker - same issue on both platforms

**Comment by zerwuff** [comment]
it would help it you could provide more debugging information, please enable "logrequestdata": "true" and set the homebridge in debug mode (-D) in the homebridge settings and provide the log without sensitive information. 
i guess the serialnumber might be wrong, since the authentication went through and the next request to fetch daily information crashes.  thanks a lot

**Comment by zerwuff** [comment]
Please check the latest version with a better error handling. If there are issues with linking your account to the serial number, it will now produce propper errors in the console and stop further requests.
