### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by CharlieVD** [zerwuff/homebridge-alphaess#16]
**Describe The Bug:**

[6/17/2024, 3:47:40 PM] [Alpha ESS Homebridge Plugin] TypeError: Cannot read properties of undefined (reading 'lastTriggerStart')
    at AlphaService.isTriggered (/volume1/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:476:23)
    at EnergyTriggerPlugin.calculateAlphaTrigger (/volume1/homebridge/node_modules/homebridge-alphaess/src/EnergyTriggerPlugin.ts:242:50)
    at EnergyTriggerPlugin.calculateCombinedTriggers (/volume1/homebridge/node_modules/homebridge-alphaess/src/EnergyTriggerPlugin.ts:132:10)
    at EnergyTriggerPlugin.onResponse (/volume1/homebridge/node_modules/homebridge-alphaess/src/EnergyTriggerPlugin.ts:96:10)
    at /volume1/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:74:27
    at Array.forEach (<anonymous>)
    at /volume1/homebridge/node_modules/homebridge-alphaess/src/alpha/AlphaService.ts:72:35
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by zerwuff** [comment]
hi, are you on the latest version ? i fixed a bug that was present for 2 hours, please check that you are up to date. br

**Comment by CharlieVD** [comment]
OK, I updated to last version. Old error is done, new error occured:
[6/17/2024, 8:04:32 PM] Homebridge v1.8.1 (HAP v0.12.0) (Alpha ESS Homebridge Plugin) is running on port 59372.
[6/18/2024, 5:36:23 AM] [Alpha ESS Homebridge Plugin] error fetching getLastPoweData, error: Error: connect ENETUNREACH 20.247.179.111:443
[6/18/2024, 5:36:23 AM] [Alpha ESS Homebridge Plugin] Error: undefined
[6/18/2024, 5:36:23 AM] [Alpha ESS Homebridge Plugin] Getting Last Power Data from Alpha Ess failed.
[6/18/2024, 10:06:37 AM] [Alpha ESS Homebridge Plugin] error fetching getLastPoweData, error: Error: connect EHOSTUNREACH 20.247.179.111:443
[6/18/2024, 10:06:37 AM] [Alpha ESS Homebridge Plugin] Error: undefined
[6/18/2024, 10:06:37 AM] [Alpha ESS Homebridge Plugin] Getting Last Power Data from Alpha Ess failed.
[6/18/2024, 12:36:14 PM] [Alpha ESS Homebridge Plugin] error fetching getLastPoweData, error: Error: connect ENETUNREACH 20.247.179.111:443
[6/18/2024, 12:36:14 PM] [Alpha ESS Homebridge Plugin] Error: undefined
[6/18/2024, 12:36:14 PM] [Alpha ESS Homebridge Plugin] Getting Last Power Data from Alpha Ess failed.

**Comment by zerwuff** [comment]
EHOSTUNREACH 20.247.179.111:443 means you could not connect to https://openapi.alphaess.com/api. 
do you have network issues or have changed something on your network side ?  for me, the site seems reachable.

**Comment by CharlieVD** [comment]
Everything is possible, I did not change network, but cannot quarantee network issues..
