### ISSUE TITLE
Plugin funktioniert nicht

### ISSUE THREAD

**Issue by Nitrox912** [zerwuff/homebridge-alphaess#3]
**Describe Your Problem:**
Es handelt sich bei mir um eine frische Installation von Homebridge und dem Alphaess Plugin. Nach Eingabe der Zugangsdaten und der Seriennummern kommt es immer wieder zu Abbrüchen und Fehlern. Es werden keine Daten angezeigt.

**Logs:**

```
TypeError: Cannot read properties of undefined (reading 'getDailyMap')
    at EnergyTriggerPlugin.calculateCombinedTriggers (/var/lib/homebridge/node_modules/homebridge-alphaess/src/EnergyTriggerPlugin.ts:125:92)
    at new EnergyTriggerPlugin (/var/lib/homebridge/node_modules/homebridge-alphaess/src/EnergyTriggerPlugin.ts:98:10)
    at AlphaEssPlatformPlugin.accessories (/var/lib/homebridge/node_modules/homebridge-alphaess/src/index.ts:32:7)
    at /var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:534:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/var/lib/homebridge/node_modules/homebridge/src/bridgeService.ts:528:12)
    at /var/lib/homebridge/node_modules/homebridge/src/server.ts:479:42
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/var/lib/homebridge/node_modules/homebridge/src/server.ts:401:27)
    at Server.start (/var/lib/homebridge/node_modules/homebridge/src/server.ts:176:29)
```

**Plugin Config:**

Die Konfiguration ist absoluter Standard. Nur die Zugangsdaten wurden ergänzt.

**Environment:**

* **Plugin Version** 2.43.0*:
* **Homebridge Version**: 1.6.1
* **Node.js Version**:  v18.16.0
* **Operating System**:  Raspberry Pi

**Comment by zerwuff** [comment]
gefixed mit der letzten version.
